# -*- coding: utf-8 -*-
"""
Structure:|
----------
technopy/
    README.md
    setup.py
    LICENSE
    STRUCTURE
    TODO
    src/
        __init__.py
        change_this/
            roots.py
        technoteam/
            activex.py
            camera.py
            capture.py
            coordinates.py
            evaluation.py
            image.py
            labsoft.py
            region.py
            table.py
            template_image_generator.py
        variables/
            dicts.py
        useful/
            postman_pat.py
        examples/
            example.py
    data/
        lmk_spectral_responsitivities.py
"""

